import os

print("TWITTER_API_KEY:", os.getenv('TWITTER_API_KEY'))
print("TWITTER_API_SECRET_KEY:", os.getenv('TWITTER_API_SECRET_KEY'))
print("TWITTER_ACCESS_TOKEN:", os.getenv('TWITTER_ACCESS_TOKEN'))
print("TWITTER_ACCESS_TOKEN_SECRET:", os.getenv('TWITTER_ACCESS_TOKEN_SECRET'))
print("TWITTER_BEARER_TOKEN:", os.getenv('TWITTER_BEARER_TOKEN'))
